"""Build Kibernetyk Mono's website index, assets, and download ZIP.

Run from the repository root: python scripts/build_site.py
Use --regular-only for a quicker local preview.
Use --font-source fonts/ttf to package existing canonical TTFs without rebuilding.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import sys
from tempfile import TemporaryDirectory
import unicodedata
from zipfile import ZIP_DEFLATED, ZipFile

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))

from fontTools.ttLib import TTFont
from kibernetyk_mono_font_builder import build_ttf, render_glyphs
from kibernetyk_mono_font_builder.core.config import (
    FONT_METADATA,
    RELEASE_VERSION,
    VERSION,
    WEIGHT_CLASSES,
    WEIGHT_STYLE_NAMES,
    WEIGHT_WIDTHS,
)


def character_category(character: str) -> str:
    name = unicodedata.name(character, "")
    category = unicodedata.category(character)
    if category.startswith("M"):
        return "marks"
    if category.startswith("N"):
        return "numbers"
    if "CYRILLIC" in name:
        return "cyrillic"
    if "LATIN" in name:
        return "latin"
    return "symbols"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--regular-only", action="store_true")
    # Retained for existing deployment commands; all weights are now the default.
    selection.add_argument("--all-weights", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument(
        "--font-source",
        type=Path,
        help="Directory containing prebuilt KibernetykMono-*.ttf files",
    )
    parser.add_argument(
        "--release",
        default=f"v{RELEASE_VERSION}",
        help="Human-readable release label",
    )
    parser.add_argument("--output", type=Path, default=PROJECT / "docs")
    options = parser.parse_args()

    font_source = options.font_source
    if font_source is not None:
        font_source = font_source if font_source.is_absolute() else PROJECT / font_source
        font_source = font_source.resolve()
        if not font_source.is_dir():
            parser.error(f"font source directory does not exist: {font_source}")

    assets = options.output / "assets"
    fonts_dir = assets / "fonts"
    downloads = assets / "downloads"
    fonts_dir.mkdir(parents=True, exist_ok=True)
    downloads.mkdir(parents=True, exist_ok=True)
    weights = ["regular"] if options.regular_only else list(WEIGHT_WIDTHS)
    metadata = []
    css = ["/* Generated by scripts/build_site.py. Fonts are served from this site. */"]
    font_files = []
    characters = []
    glyph_count = 0
    stylistic_sets = set()

    with TemporaryDirectory(prefix="kibernetyk-site-") as temporary:
        for weight in weights:
            filename = f"KibernetykMono-{WEIGHT_STYLE_NAMES[weight]}.ttf"
            if font_source is None:
                glyphs = render_glyphs(WEIGHT_WIDTHS[weight], rounded=False)
                compiled = build_ttf(
                    glyphs, Path(temporary) / filename, weight, rounded=False
                )
            else:
                compiled = font_source / filename
                if not compiled.is_file():
                    parser.error(f"missing font: {compiled}")

            digest = hashlib.sha256(compiled.read_bytes()).hexdigest()[:12]
            destination = fonts_dir / filename
            if compiled.resolve() != destination.resolve():
                shutil.copyfile(compiled, destination)
            font_files.append(destination)
            css.append(
                "@font-face {\n"
                '  font-family: "Kibernetyk Web";\n'
                f'  src: url("./fonts/{filename}?v={digest}") format("truetype");\n'
                f"  font-weight: {WEIGHT_CLASSES[weight]};\n"
                "  font-style: normal;\n"
                "  font-display: swap;\n"
                "}\n"
            )
            metadata.append({
                "family": "Kibernetyk Web",
                "weight": WEIGHT_CLASSES[weight],
                "style": WEIGHT_STYLE_NAMES[weight],
            })
            if weight == "regular":
                with TTFont(compiled) as font:
                    glyph_count = len(font.getGlyphOrder())
                    if "GSUB" in font and font["GSUB"].table.FeatureList:
                        stylistic_sets = {
                            feature.FeatureTag
                            for feature in font["GSUB"].table.FeatureList.FeatureRecord
                            if re.fullmatch(r"ss(?:0[1-9]|1[0-9]|20)", feature.FeatureTag)
                        }
                    for codepoint, glyph_name in sorted(font.getBestCmap().items()):
                        character = chr(codepoint)
                        characters.append({
                            "codepoint": codepoint,
                            "character": character,
                            "unicode": f"U+{codepoint:04X}",
                            "name": unicodedata.name(character, glyph_name),
                            "glyphName": glyph_name,
                            "category": character_category(character),
                        })
            print(f"Font: {destination.relative_to(options.output)}")

    for filename in ("OFL.txt", "AUTHORS.txt"):
        shutil.copyfile(PROJECT / filename, downloads / filename)
    archive = downloads / "KibernetykMono.zip"
    with ZipFile(archive, "w", ZIP_DEFLATED) as bundle:
        for font in font_files:
            bundle.write(font, "KibernetykMono/" + font.name)
        for filename in ("OFL.txt", "AUTHORS.txt"):
            bundle.write(PROJECT / filename, "KibernetykMono/" + filename)
        bundle.writestr(
            "KibernetykMono/README.txt",
            f"Kibernetyk Mono {options.release}\n"
            f"Designed by {FONT_METADATA['designer']}.\n\n"
            "Install the TTF files using your operating system's font manager.\n"
            "Select Kibernetyk Mono in your editor.\n\n"
            f"Source: {FONT_METADATA['vendorURL']}\n"
            "Licensed under the SIL Open Font License 1.1. See OFL.txt.\n",
        )
    scripts = [
        script.title() for script in ("latin", "cyrillic")
        if any(character["category"] == script for character in characters)
    ]
    weight_label = "Regular" if options.regular_only else f"{len(weights)} weights"
    manifest = {
        "release": options.release,
        "fontVersion": VERSION,
        "fonts": metadata,
        "characters": characters,
        "glyphCount": glyph_count,
        "stylisticSetCount": len(stylistic_sets),
        "scripts": scripts,
        "download": "./assets/downloads/KibernetykMono.zip",
        "downloadDescription": f"{weight_label} · TTF · {options.release}",
    }
    (assets / "fonts.css").write_text("\n".join(css), encoding="utf-8")
    # A normal script also works when index.html is opened directly as a file.
    (assets / "font-data.js").write_text(
        "// Generated by scripts/build_site.py.\nwindow.KIBERNETYK_SITE = " +
        json.dumps(manifest, ensure_ascii=True, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Site ready: {options.output / 'index.html'}")
    print(
        f"{glyph_count} glyphs; {len(characters)} encoded characters; "
        f"{len(font_files)} fonts in {archive.name}."
    )


if __name__ == "__main__":
    main()
